version: '3.7'

services:
  robomaker:
    networks:
      - sagemaker-local
      - bridge
    deploy:
      replicas: ${DR_WORKERS}
    volumes:
      - "${DR_DIR}/tmp/comms.${DR_RUN_ID}:/mnt/comms"
