version: '3.7'

services:
  rl_coach:
    deploy:
      restart_policy:
        condition: none
  robomaker:
    deploy:
      restart_policy:
        condition: none
      replicas: ${DR_WORKERS}
    environment:
        - DOCKER_REPLICA_SLOT={{.Task.Slot}}