version: '3.7'

networks:
  default:
    external:
      name: sagemaker-local

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    container_name: minio
    command: gateway azure
    restart: unless-stopped
    env_file: .env
  minio-log:
    image: minio/minio
    ports:
      - "9001:9001"
    container_name: minio-log
    command: server --address :9001 /data
    volumes:
      - /mnt/deepracer/robo/checkpoint:/data
    restart: unless-stopped
    env_file: .env
  rl_coach:
    image: aschu/rl_coach
    env_file: .env
    container_name: rl_coach
    volumes:
    - '//var/run/docker.sock:/var/run/docker.sock'
    - '../deepracer/sagemaker-python-sdk:/deepracer/sagemaker-python-sdk'
    - '../deepracer/rl_coach:/deepracer/rl_coach'
    - '/mnt/deepracer/robo/container:/robo/container'
    depends_on:
    - minio
  robomaker:
    image: larsll/deepracer_robomaker:latest
    command: ["${ROBOMAKER_COMMAND}"]
    volumes:
      - ../deepracer/simulation/aws-robomaker-sample-application-deepracer/simulation_ws/src:/app/robomaker-deepracer/simulation_ws/src
      - /mnt/deepracer/robo/checkpoint:/root/.ros/
      - /mnt/recording:/mnt/recording
    ports:
      - "8080:5900"
    container_name: robomaker
    restart: unless-stopped
    env_file: .env
    depends_on:
    - rl_coach
