version: '3.7'

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    command: server /data
    restart: unless-stopped
    environment:
      - MINIO_ACCESS_KEY=${DR_LOCAL_ACCESS_KEY_ID}
      - MINIO_SECRET_KEY=${DR_LOCAL_SECRET_ACCESS_KEY}
    volumes:
      - ${DR_DIR}/docker/volumes/minio:/data

