version: '3.7'

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    container_name: minio
    command: gateway azure
    restart: unless-stopped
    environment:
      - MINIO_ACCESS_KEY=${DR_LOCAL_ACCESS_KEY_ID}
      - MINIO_SECRET_KEY=${DR_LOCAL_SECRET_ACCESS_KEY}
      - AWS_ACCESS_KEY_ID=${DR_LOCAL_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${DR_LOCAL_SECRET_ACCESS_KEY}

